spring: 
    datasource:
        generate-unique-id: false
        name: patientreg
        url: jdbc:h2:mem:patientreg
    jpa:
        show-sql: true
        format-sql: true
        hibernate:
            ddl-auto: none



